version: "3"
services:
  api:
    image: certi-test-ivan
    build: .
    networks:
      - backend
    ports:
      - "3000:3000"

  web-cli:
    image: certi-test-ivan
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge
