const words = {
  and: ' e ',
  nameHundred: 'cem',
  nameThousand: 'mil',
  names: [
    [],
    [
      '',
      'um',
      'dois',
      'trÃªs',
      'quatro',
      'cinco',
      'seis',
      'sete',
      'oito',
      'nove',
    ],
    [
      '',
      'dez',
      'vinte',
      'trinta',
      'quarenta',
      'cinquenta',
      'sessenta',
      'setenta',
      'oitenta',
      'noventa',
      'dez',
      'onze',
      'doze',
      'treze',
      'quatorze',
      'quinze',
      'dezesseis',
      'dezessete',
      'dezoito',
      'dezenove',
    ],
    [
      '',
      'cento',
      'duzentos',
      'trezentos',
      'quatrocentos',
      'quinhentos',
      'seiscentos',
      'setecentos',
      'oitocentos',
      'novecentos',
    ],
  ],
  nameZero: 'zero',
  negative: 'menos ',
};
